// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Home → navbar link*
 */
export interface HomeDocumentDataNavbarLinkItem {
  /**
   * navbar link text field in *Home → navbar link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navbar_link[].navbar_link_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  navbar_link_text: prismic.KeyTextField;

  /**
   * navbar link field in *Home → navbar link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navbar_link[].navbar_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navbar_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Home → hero section*
 */
export interface HomeDocumentDataHeroSectionItem {
  /**
   * background hero image field in *Home → hero section*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_section[].background_hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_hero_image: prismic.ImageField<never>;

  /**
   * hero text field in *Home → hero section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get Inspired, Cook with passion and enjoy unforgettable moments at the table
   * - **API ID Path**: home.hero_section[].hero_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_text: prismic.KeyTextField;
}

/**
 * Item in *Home → socials icons*
 */
export interface HomeDocumentDataSocialsIconsItem {
  /**
   * icon1 field in *Home → socials icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.socials_icons[].icon1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon1: prismic.ImageField<never>;

  /**
   * icon2 field in *Home → socials icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.socials_icons[].icon2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon2: prismic.ImageField<never>;

  /**
   * icon3 field in *Home → socials icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.socials_icons[].icon3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon3: prismic.ImageField<never>;

  /**
   * icon4 field in *Home → socials icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.socials_icons[].icon4
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon4: prismic.ImageField<never>;
}

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * website logo field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.website_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  website_logo: prismic.ImageField<never>;

  /**
   * website name field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Delícias à Mesa
   * - **API ID Path**: home.website_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  website_name: prismic.KeyTextField;

  /**
   * navbar link field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navbar_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navbar_link: prismic.GroupField<Simplify<HomeDocumentDataNavbarLinkItem>>;

  /**
   * section one text field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Popular Recipes
   * - **API ID Path**: home.section_one_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_one_text: prismic.KeyTextField;

  /**
   * hero section field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  hero_section: prismic.GroupField<Simplify<HomeDocumentDataHeroSectionItem>>;

  /**
   * Section two text field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Recent Recipes
   * - **API ID Path**: home.section_two_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_two_text: prismic.KeyTextField;

  /**
   * footer text field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Redes sociais:
   * - **API ID Path**: home.footer_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_text: prismic.KeyTextField;

  /**
   * socials icons field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.socials_icons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socials_icons: prismic.GroupField<Simplify<HomeDocumentDataSocialsIconsItem>>;

  /**
   * nav search bar placeholder field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search
   * - **API ID Path**: home.nav_search_bar_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_search_bar_placeholder: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Search Recipes documents
 */
interface SearchRecipesDocumentData {
  /**
   * Main heading field in *Search Recipes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Search Recipes
   * - **API ID Path**: search_recipes.main_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * placeholder text for search bar field in *Search Recipes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search for recipes...
   * - **API ID Path**: search_recipes.placeholder_text_for_search_bar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder_text_for_search_bar: prismic.KeyTextField;

  /**
   * text when no search field in *Search Recipes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter a search term to find recipes.
   * - **API ID Path**: search_recipes.text_when_no_search
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_when_no_search: prismic.KeyTextField;

  /**
   * Results heading field in *Search Recipes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Results for:
   * - **API ID Path**: search_recipes.results_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  results_heading: prismic.KeyTextField;

  /**
   * no recipes found field in *Search Recipes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: No recipes found. Try a different search term.
   * - **API ID Path**: search_recipes.no_recipes_found
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  no_recipes_found: prismic.KeyTextField;
}

/**
 * Search Recipes document from Prismic
 *
 * - **API ID**: `search_recipes`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchRecipesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SearchRecipesDocumentData>,
    "search_recipes",
    Lang
  >;

export type AllDocumentTypes = HomeDocument | SearchRecipesDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataNavbarLinkItem,
      HomeDocumentDataHeroSectionItem,
      HomeDocumentDataSocialsIconsItem,
      SearchRecipesDocument,
      SearchRecipesDocumentData,
      AllDocumentTypes,
    };
  }
}
