// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutUsDocumentDataSlicesSlice = OurMissionSlice | PageHeaderSlice;

/**
 * Content for About Us documents
 */
interface AboutUsDocumentData {
  /**
   * meta title field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: meta data title for the about us page
   * - **API ID Path**: about_us.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * meta description field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: meta data description for the about us page
   * - **API ID Path**: about_us.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *About Us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutUsDocumentDataSlicesSlice>;
}

/**
 * About Us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutUsDocumentData>,
    "about_us",
    Lang
  >;

/**
 * Item in *Home → navbar link*
 */
export interface HomeDocumentDataNavbarLinkItem {
  /**
   * navbar link text field in *Home → navbar link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navbar_link[].navbar_link_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  navbar_link_text: prismic.KeyTextField;

  /**
   * Page Link field in *Home → navbar link*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navbar_link[].page_link
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  page_link: prismic.ContentRelationshipField;
}

/**
 * Item in *Home → hero section*
 */
export interface HomeDocumentDataHeroSectionItem {
  /**
   * background hero image field in *Home → hero section*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_section[].background_hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_hero_image: prismic.ImageField<never>;

  /**
   * hero text field in *Home → hero section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get Inspired, Cook with passion and enjoy unforgettable moments at the table
   * - **API ID Path**: home.hero_section[].hero_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_text: prismic.KeyTextField;

  /**
   * background hero image mobile field in *Home → hero section*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_section[].background_hero_image_mobile
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_hero_image_mobile: prismic.ImageField<never>;
}

/**
 * Item in *Home → socials icons*
 */
export interface HomeDocumentDataSocialsIconsItem {
  /**
   * icon1 field in *Home → socials icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.socials_icons[].icon1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon1: prismic.ImageField<never>;

  /**
   * icon2 field in *Home → socials icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.socials_icons[].icon2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon2: prismic.ImageField<never>;

  /**
   * icon3 field in *Home → socials icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.socials_icons[].icon3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon3: prismic.ImageField<never>;

  /**
   * icon4 field in *Home → socials icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.socials_icons[].icon4
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon4: prismic.ImageField<never>;
}

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * website logo field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.website_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  website_logo: prismic.ImageField<never>;

  /**
   * website name field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Delícias à Mesa
   * - **API ID Path**: home.website_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  website_name: prismic.KeyTextField;

  /**
   * navbar link field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navbar_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navbar_link: prismic.GroupField<Simplify<HomeDocumentDataNavbarLinkItem>>;

  /**
   * section one text field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Popular Recipes
   * - **API ID Path**: home.section_one_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_one_text: prismic.KeyTextField;

  /**
   * hero section field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  hero_section: prismic.GroupField<Simplify<HomeDocumentDataHeroSectionItem>>;

  /**
   * Section two text field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Recent Recipes
   * - **API ID Path**: home.section_two_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_two_text: prismic.KeyTextField;

  /**
   * footer text field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Redes sociais:
   * - **API ID Path**: home.footer_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_text: prismic.KeyTextField;

  /**
   * socials icons field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.socials_icons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socials_icons: prismic.GroupField<Simplify<HomeDocumentDataSocialsIconsItem>>;

  /**
   * nav search bar placeholder field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search
   * - **API ID Path**: home.nav_search_bar_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_search_bar_placeholder: prismic.KeyTextField;

  /**
   * card button text field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View Recipe
   * - **API ID Path**: home.card_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_button_text: prismic.KeyTextField;

  /**
   * meta tile field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: recipe app
   * - **API ID Path**: home.meta_tile
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_tile: prismic.KeyTextField;

  /**
   * meta description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: here is your meta description
   * - **API ID Path**: home.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Not Found documents
 */
interface NotFoundDocumentData {
  /**
   * main heading field in *Not Found*
   *
   * - **Field Type**: Text
   * - **Placeholder**: h1 heading
   * - **API ID Path**: not_found.main_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  main_heading: prismic.KeyTextField;

  /**
   * paragraph text field in *Not Found*
   *
   * - **Field Type**: Text
   * - **Placeholder**: subsection paragraph
   * - **API ID Path**: not_found.paragraph_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  paragraph_text: prismic.KeyTextField;

  /**
   * button text field in *Not Found*
   *
   * - **Field Type**: Text
   * - **Placeholder**: button text to return back to home
   * - **API ID Path**: not_found.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Not Found*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: not_found.button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  button_link: prismic.ContentRelationshipField<"home">;
}

/**
 * Not Found document from Prismic
 *
 * - **API ID**: `not_found`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NotFoundDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NotFoundDocumentData>,
    "not_found",
    Lang
  >;

/**
 * Content for Recipe Details documents
 */
interface RecipeDetailsDocumentData {
  /**
   * ingredients field in *Recipe Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ingredients
   * - **API ID Path**: recipe_details.ingredients
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ingredients: prismic.KeyTextField;

  /**
   * instructions field in *Recipe Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Instructions
   * - **API ID Path**: recipe_details.instructions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  instructions: prismic.KeyTextField;

  /**
   * summary field in *Recipe Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Summary
   * - **API ID Path**: recipe_details.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  summary: prismic.KeyTextField;

  /**
   * ready in field in *Recipe Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ready in
   * - **API ID Path**: recipe_details.ready_in_minutes
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ready_in_minutes: prismic.KeyTextField;

  /**
   * no instructions available field in *Recipe Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: No Instructions Available
   * - **API ID Path**: recipe_details.no_instructions_available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  no_instructions_available: prismic.KeyTextField;

  /**
   * minutes field in *Recipe Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Minutes
   * - **API ID Path**: recipe_details.minutes
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  minutes: prismic.KeyTextField;

  /**
   * similar Recipes field in *Recipe Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Similar Recipes
   * - **API ID Path**: recipe_details.similar_recipes
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  similar_recipes: prismic.KeyTextField;
}

/**
 * Recipe Details document from Prismic
 *
 * - **API ID**: `recipe_details`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RecipeDetailsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RecipeDetailsDocumentData>,
    "recipe_details",
    Lang
  >;

/**
 * Content for Search Recipes documents
 */
interface SearchRecipesDocumentData {
  /**
   * Main heading field in *Search Recipes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Search Recipes
   * - **API ID Path**: search_recipes.main_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * placeholder text for search bar field in *Search Recipes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search for recipes...
   * - **API ID Path**: search_recipes.placeholder_text_for_search_bar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder_text_for_search_bar: prismic.KeyTextField;

  /**
   * text when no search field in *Search Recipes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter a search term to find recipes.
   * - **API ID Path**: search_recipes.text_when_no_search
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_when_no_search: prismic.KeyTextField;

  /**
   * Results heading field in *Search Recipes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Results for:
   * - **API ID Path**: search_recipes.results_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  results_heading: prismic.KeyTextField;

  /**
   * no recipes found field in *Search Recipes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: No recipes found. Try a different search term.
   * - **API ID Path**: search_recipes.no_recipes_found
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  no_recipes_found: prismic.KeyTextField;

  /**
   * next button text field in *Search Recipes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Next
   * - **API ID Path**: search_recipes.next_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  next_button_text: prismic.KeyTextField;

  /**
   * prev button text field in *Search Recipes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Previous
   * - **API ID Path**: search_recipes.prev_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  prev_button_text: prismic.KeyTextField;
}

/**
 * Search Recipes document from Prismic
 *
 * - **API ID**: `search_recipes`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchRecipesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SearchRecipesDocumentData>,
    "search_recipes",
    Lang
  >;

export type AllDocumentTypes =
  | AboutUsDocument
  | HomeDocument
  | NotFoundDocument
  | RecipeDetailsDocument
  | SearchRecipesDocument;

/**
 * Primary content in *OurMission → Default → Primary*
 */
export interface OurMissionSliceDefaultPrimary {
  /**
   * heading field in *OurMission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: heading for the Our Mission section
   * - **API ID Path**: our_mission.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Our Mission Image field in *OurMission → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_mission.default.primary.our_mission_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  our_mission_image: prismic.ImageField<never>;

  /**
   * content of our mission field in *OurMission → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: the main content of the our mission heading
   * - **API ID Path**: our_mission.default.primary.content_of_our_mission
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content_of_our_mission: prismic.RichTextField;
}

/**
 * Default variation for OurMission Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurMissionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurMissionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurMission*
 */
type OurMissionSliceVariation = OurMissionSliceDefault;

/**
 * OurMission Shared Slice
 *
 * - **API ID**: `our_mission`
 * - **Description**: OurMission
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurMissionSlice = prismic.SharedSlice<
  "our_mission",
  OurMissionSliceVariation
>;

/**
 * Primary content in *PageHeader → Default → Primary*
 */
export interface PageHeaderSliceDefaultPrimary {
  /**
   * title field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Delícias à Mesa About Us
   * - **API ID Path**: page_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: description of Delícias à Mesa
   * - **API ID Path**: page_header.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageHeader*
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;

/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: PageHeader
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageHeaderSlice = prismic.SharedSlice<
  "page_header",
  PageHeaderSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataNavbarLinkItem,
      HomeDocumentDataHeroSectionItem,
      HomeDocumentDataSocialsIconsItem,
      NotFoundDocument,
      NotFoundDocumentData,
      RecipeDetailsDocument,
      RecipeDetailsDocumentData,
      SearchRecipesDocument,
      SearchRecipesDocumentData,
      AllDocumentTypes,
      OurMissionSlice,
      OurMissionSliceDefaultPrimary,
      OurMissionSliceVariation,
      OurMissionSliceDefault,
      PageHeaderSlice,
      PageHeaderSliceDefaultPrimary,
      PageHeaderSliceVariation,
      PageHeaderSliceDefault,
    };
  }
}
