// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  our_mission: dynamic(() => import("./OurMission")),
  page_header: dynamic(() => import("./PageHeader")),
};
