import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/styles/globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { createClient } from "@/prismicio";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();
  const homeData = await client.getSingle("home");
  return (
    <html lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body>
      <Nav page={homeData} />
        {children}
      <Footer page={homeData} />
      </body>
    </html>
  );
}
